export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';




export const SOCKET_ACCOUNT_DEACTIVATED_SUCCESS = 'SOCKET_ACCOUNT_DEACTIVATED_SUCCESS';



export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';



export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';

export const ERROR = 'ERROR';
