export const SET_STRIPE_LOADING = "SET_STRIPE_LOADING";

export const STRIPE_PAY_SUCCESS = "STRIPE_PAY_SUCCESS";
export const STRIPE_PAY_FAIL = "STRIPE_PAY_FAIL";

export const STRIPE_PAYMENT_DETAIL_SUCCESS = "STRIPE_PAYMENT_DETAIL_SUCCESS";


