export const SET_USER_LOADING = "SET_USER_LOADING";

export const GET_BINANCE_EXCHANGE_ASSETES_SUCCESS = "GET_BINANCE_EXCHANGE_ASSETES_SUCCESS";
export const GET_BITPANDAPRO_EXCHANGE_ASSETES_SUCCESS = "GET_BITPANDAPRO_EXCHANGE_ASSETES_SUCCESS";
export const GET_POLONIEX_EXCHANGE_ASSETES_SUCCESS = "GET_POLONIEX_EXCHANGE_ASSETES_SUCCESS";
export const GET_KRAKEN_EXCHANGE_ASSETES_SUCCESS = "GET_KRAKEN_EXCHANGE_ASSETES_SUCCESS";
export const GET_OKEX_EXCHANGE_ASSETES_SUCCESS = "GET_OKEX_EXCHANGE_ASSETES_SUCCESS";



export const GET_EXCHANGE_ASSETS_FAIL = "GET_EXCHANGE_ASSETS_FAIL";


