export const SET_USER_LOADING = "SET_USER_LOADING";

export const GET_EXCHANGE_ASSETS_SUCCESSFULL = "GET_EXCHANGE_ASSETS_SUCCESSFULL";
export const GET_EXCHANGE_ASSETS_FAIL = "GET_EXCHANGE_ASSETS_FAIL";


