export const SET_USER_LOADING = "SET_USER_LOADING";

export const GET_BINANCE_EXCHANGE_ASSETES_SUCCESS = "GET_EXCHANGE_ASSETS_SUCCESSFULL";



export const GET_EXCHANGE_ASSETS_FAIL = "GET_EXCHANGE_ASSETS_FAIL";


