export const SET_BALANCE_LOADING = 'SET_BALANCE_LOADING';

export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';

export const GET_EXCHANGE_KEY_SUCCESS = 'GET_EXCHANGE_KEY_SUCCESS'
export const GET_EXCHANGE_KEY_FAILED = 'GET_EXCHANGE_KEY_FAILED'