
export const RULE_LOADING = 'RULE_LOADING'
export const RULE_ERROR = 'RULE_ERROR'

export const COIN_LOSS = 'SET_EXCHANGE_LOSS'
export const COIN_PROFIT = 'SET_EXCHANGE_PROFIT'

export const SET_DIRECT_ORDER_RULE = 'SET_DIRECT_ORDER_RULE'

export const RULE_LISTING_SUCCESS = 'RULE_LISTING_SUCCESS'