export const SET_EXCHANGE_LOADING = 'SET_EXCHANGE_LOADING';
export const CONNECT_EXCHANGE_SUCCESS = 'CONNECT_EXCHANGE_SUCCESS';
export const CONNECT_EXCHANGE_FAIL = 'CONNECT_EXCHANGE_FAIL';
export const GET_EXCHANGES_SUCCESS = 'GET_EXCHANGES_SUCCESS';
export const GET_EXCHANGESS_FAIL = 'GET_EXCHANGESS_FAIL';


export const DELETE_USER_EXCHANGE_SUCCESS = 'DELETE_USER_EXCHANGE_SUCCESS';
export const DELETE_USER_EXCHANGE_FAIL = 'DELETE_USER_EXCHANGE_FAIL';
